general:
  project_name: my_db_project
filename:
  save_data_root_directory_name: '/var/tmp'
  structure_directory_name: 'structure'
  structure_dump_fiilename: 'my_db.structure.dump'
  table_data_directory_name: 'table_data'
  table_data_dump_filename_prefix: 'my_db.table_data'
source_db:
  host: '192.168.1.10'
  port: 3306
  dbname: 'foo_db'
  # only with read authentication to get table names
  readonly_username: 'foofoo'
  readonly_user_password: 'barbar'
  # it is necessary to exec mysqldump command
  root_username: 'hoge'
  root_user_password: 'fuga'
target_db:
  host: '192.168.1.20'
  port: 3306
  dbname: 'bar_db'
  root_username: 'hogehoge'
  root_user_password: 'fugafuga'
